version: 2
jobs:
    build-test:
        docker:
            - image: circleci/node:8
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
    deploy-production:
        docker:
            - image: circleci/node:8
        steps:
            - deploy:
                name: Deploy to production
                command: ssh -o "StrictHostKeyChecking no" $SSH_DETAILS "cd $LOCATION; git pull; npm install;"
workflows:
    version: 2
    build-deploy:
        jobs:
            - build-test
            - deploy-production:
                requires:
                    - build-test
                filters:
                    branches:
                        only: master